function [ res ] = annotaion_value()
%ANNOTAION_VALUE Return a cell array contatining all the possible names of
%annotation file

res = { 'BA.annot'                 'overlap.annot'...		    
               'bert_ref.aparc.annot'     'aparc.a2009s.annot'...
               'aparc.annot'              'aparc.DKTatlas40.annot'  ...	 
               'BA.thresh.annot'          'bert_ref.aparc.a2009s.annot'...
               'bert_ref.aparc.annot'...
              };


end

