function [ res ] = curvature_value()
%CURVATURE_VALUE Return a cell array contatining all the possible names of
%curvature file

res = { 'area',             'sulc', ...
        'thickness',        'area.pial',...
        'volume',           'avg_curv',...
        'smoothwm',         'curv',...
        'smoothwm.BE.crv',  'curv.pial',...
        'smoothwm.C.crv',   'defect_borders',...
        'smoothwm.FI.crv',  'defect_chull',...
        'smoothwm.H.crv',   'defect_labels',...
        'smoothwm.K1.crv',  'smoothwm.K2.crv',  ...
        'inflated.H',       'smoothwm.K.crv',...  
        'inflated.K',       'smoothwm.S.crv',... 
        'jacobian_white',   'area.mid'...
        };

end

