function [ res ] = parc_region_value()
%PARC_REGION_VALUE Return a cell array contatining all the possible names of
%parc region,these values should be in the same order of values returned by
%RGB_label_value_parc.m


res = {'unknown',              'bankssts',            'caudalanteriorcingulate',...  
       'caudalmiddlefrontal',  'corpuscallosum',      'cuneus',...                  
       'entorhinal',           'fusiform',            ...        
       'inferiortemporal',     'isthmuscingulate',    'lateraloccipital',...        
       'lateralorbitofrontal', 'lingual',             'medialorbitofrontal',...     
       'middletemporal',       'parahippocampal',     'paracentral',...             
       'parsopercularis',      'parsorbitalis',       'parstriangularis',...        
       'pericalcarine',        'postcentral',         'posteriorcingulate',...      
       'precentral',           'precuneus',           'rostralanteriorcingulate',...
       'rostralmiddlefrontal', 'superiorfrontal',     'superiorparietal',...        
       'superiortemporal',     'supramarginal',       'frontalpole',...             
       'temporalpole',         'transversetemporal',  'insula',...
       'UNKNOWN'     ,         'inferiorparietal'};


end

