function [ regions ] = regions_rosas( hemi )
%REGIONS_ROSAS return the list of the most affected region accoreding to
%Rosas et. al. 2011, given the hemisphere

%%
if strcmp(hemi,'lh')
    regions = {'caudalmiddlefrontal','rostralmiddlefrontal','parsorbitalis',...
        'parstriangularis','parsopercularis','precentral','supramarginal',...
        'inferiorparietal','precuneus','isthmuscingulate','superiortemporal',...
        'middletemporal','inferiortemporal','parahippocampal','lingual',...
        'fusiform','lateraloccipital'};
else if strcmp(hemi,'rh')
        regions = {'superiorfrontal','caudalmiddlefrontal','rostralmiddlefrontal',...
            'parsorbitalis','parstriangularis','parsopercularis',...
            'caudalanteriorcingulate','rostralanteriorcingulate',...
            'precentral','postcentral','supramarginal','superiorparietal',...
            'paracentral','inferiorparietal','precuneus','isthmuscingulate',...
            'superiortemporal','middletemporal','inferiortemporal',...
            'parahippocampal','lingual','fusiform','lateraloccipital'};
    else
        erro('Hemi %s does not exists',hemi);
    end
end

end

