function [ res ] = surf_value()
%SURF_VALUE Return a cell array contatining all the possible names of
%surface file

res = { 'inflated',        'inflated.nofix',...
         'inflated.nofix',  'orig',          ...
         'orig.nofix',      'pial',...
         'qsphere.nofix',   'smoothwm',...
         'sphere',          'sphere.reg',...
         'white',...
         };

end

