function [v_curv, fnum] = load_curvature_file( subjet , number )
%LOAD_CURVATURE_FILE Load a curvature file for subject 


curv = {'lh.area',             'lh.sulc',            'rh.smoothwm.K2.crv',...
        'lh.thickness',        'rh.inflated.H',      'rh.smoothwm.K.crv',...
        'lh.area.pial',        'lh.volume',          'rh.inflated.K',...
        'lh.avg_curv',         'lh.smoothwm',        'rh.smoothwm.S.crv',...
        'lh.curv',             'lh.smoothwm.BE.crv', 'rh.jacobian_white',...
        'lh.curv.pial',        'lh.smoothwm.C.crv',  'lh.defect_borders',...
        'lh.smoothwm.FI.crv',  'rh.area','rh.sulc',  'lh.defect_chull',...
        'lh.smoothwm.H.crv',   'rh.thickness',       'lh.defect_labels',...
        'lh.smoothwm.K1.crv',  'rh.area.pial',       'rh.volume',...
        'lh.smoothwm.K2.crv',  'rh.avg_curv',        'rh.smoothwm',...
        'lh.inflated.H',       'lh.smoothwm.K.crv',  'rh.curv',...
        'rh.smoothwm.BE.crv',  'lh.inflated.K',      'rh.curv.pial',...
        'rh.smoothwm.C.crv',   'lh.smoothwm.S.crv',  'rh.defect_borders',...
        'rh.smoothwm.FI.crv',  'lh.jacobian_white',  'rh.defect_chull',...
        'rh.smoothwm.H.crv',   'rh.defect_labels',   'rh.smoothwm.K1.crv'};

path_complete_crv = [subjet.path,'surf/',curv{number}];
[v_curv, fnum] = read_curv(path_complete_crv);


v_curv = remove_curv_outliers(v_curv);
v_curv = change_range(v_curv);

end

