function [vertices, faces] = load_surface_file( subject , number )
%LOAD_SURFACE_FILE Load a surface file for subject

surf = { 'lh.inflated',        'rh.inflated',      'lh.inflated.nofix',...
         'rh.inflated.nofix',  'lh.orig',          'rh.orig',...
         'lh.orig.nofix',      'rh.orig.nofix',    'lh.pial',...
         'lh.qsphere.nofix',   'rh.qsphere.nofix', 'lh.smoothwm',...
         'rh.smoothwm',        'lh.sphere',        'rh.sphere',...
         'lh.sphere.reg',      'rh.sphere.reg',    'lh.white',...
         'rh.white'            'rh.pial'};

path_complete_srf = [subject.path,'surf/',surf{number}];
[vertices, faces] = freesurfer_read_surf(path_complete_srf);

vertices = addSphericalCoord( vertices );

end

