label = { 'lh.BA3b.thresh.label'	     'lh.cortex.label'		               'rh.BA2.label'...	      
          'rh.BA6.thresh.label'          'lh.BA44.label'		               'lh.entorhinal_exvivo.label'...
          'rh.BA2.thresh.label'          'lh.BA44.thresh.label'	               'lh.MT.label'...
          'rh.BA3a.label'	             'rh.BA.thresh.annot lh.BA45.label'	   'lh.MT.thresh.label'...	
          'rh.BA3a.thresh.label'         'lh.BA4a.label'		               'lh.perirhinal.label'...	 
          'rh.BA3b.thresh.label'         'rh.cortex.label'                     'lh.BA4a.thresh.label'...	
          'lh.V1.label'		             'rh.BA44.label'	                   'rh.entorhinal_exvivo.label'... 
          'lh.BA4p.label'		         'lh.V1.thresh.label'		           'rh.BA44.thresh.label'...  
          'rh.MT.label'                  'lh.BA1.label'		                   'lh.BA4p.thresh.label'...	     
          'lh.V2.label'		             'rh.BA45.label'	                   'rh.MT.thresh.label'...
          'lh.BA1.thresh.label'	         'lh.BA6.label'		                   'lh.V2.thresh.label'...		
          'rh.BA45.thresh.label'         'lh.BA2.label'		                   'lh.BA6.thresh.label'...	     
          'rh.BA3b.label'	             'lh.BA45.thresh.label'	               'rh.BA4a.label'...	       
          'rh.perirhinal.label'          'rh.BA4a.thresh.label'                'rh.V1.label'...
          'lh.BA2.thresh.label'	         'lh.BA3a.label'		     	       'rh.BA4p.label'...	       
          'rh.V1.thresh.label'           'lh.BA3a.thresh.label'	               'rh.BA1.label'...
          'rh.BA4p.thresh.label'         'rh.V2.label'                         'rh.BA1.thresh.label'...
          'rh.BA6.label'	             'rh.V2.thresh.label'                  'lh.BA3b.label'};
 ctab = {'aparc.annot.a2009s.ctab'     'aparc.annot.ctab'	  'aparc.annot.DKTatlas40.ctab'...
         'BA.ctab'			           'BA.thresh.ctab'        };
      
