function print_mean_log_likelihood(values,region,index)
%print single region
for ii=1:length(index)
    disp([region{index(ii)} ,...
        '  ', num2str(values(ii,5)),...
        '  ', num2str(values(ii,[2,1])),...
        '  ', num2str(values(ii,2)-values(ii,1)),...        
        '  ', num2str(values(ii,6)),....
        '  ', num2str(values(ii,[4,3])),...
        '  ', num2str(values(ii,4)-values(ii,3))]);
end
%print mean
mean_trhes_p1 = mean(values(:,5));
mean_v2_p1 = mean(values(:,2));
mean_v3_p1 = mean(values(:,1));
mean_v2_v3_p1 = mean(values(:,2) - values(:,1));
mean_trhes_p2 = mean(values(:,6));
mean_v2_p2 = mean(values(:,4));
mean_v3_p2 = mean(values(:,3));
mean_v2_v3_p2 = mean(values(:,4) - values(:,3));

disp(['mean' ,...
    '  ', num2str(mean_trhes_p1),...
    '  ', num2str([mean_v2_p1,mean_v3_p1]),...
    '  ', num2str(mean_v2_v3_p1),...
    '  ', num2str(mean_trhes_p2),...
    '  ', num2str([mean_v2_p2,mean_v3_p2]),...
    '  ', num2str(mean_v2_v3_p2)]);

end